name: Bundle Webpack

on:
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  bundle-webpack:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v2
    -
      uses: actions/setup-node@v2
      with:
        node-version: 16.14.2
    - run: npm install 
    - run: npm run bootstrap -- --no-ci
    - run: npm run build -- --no-ci
    -
      working-directory: packages/taquito-local-forging
      run: npm run build-webpack
    -
      uses: actions/upload-artifact@v3
      with:
        name: taquito-local-forging-mobilefriendly
        path: |
          packages/taquito-local-forging/dist/taquito_local_forging.js
          packages/taquito-local-forging/dist/taquito_local_forging.js.map
