# TODO: Delete this file and include in main.yml after testing succeedes
name: Node.js CI

on:
  push:

jobs:
  flextesa-limabox:
    runs-on: ubuntu-latest
    continue-on-error: true

    container:
      image: oxheadalpha/flextesa:latest

    steps:
    - run: flextesa mini-net --root /tmp/mini-box --size 1 --set-history-mode N000:archive --number-of-b 1 --balance-of-bootstrap-accounts tez:100_000_000 --time-b "$time_bb" --add-bootstrap-account="alice,edpkvGfYw3LyB1UcCahKQk4rF2tvbMUk8GFiTuMjL75uGXrpvKXhjn,tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb,unencrypted:edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq@2_000_000_000_000" --add-bootstrap-account="$bob,edpkurPsQ8eUApnLUJ9ZPDvu98E8VNj4KtJa1aZr16Cr5ow5VHKnz4,tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6,unencrypted:edsk3RFfvaFaxbHx8BMtEW1rKQcPtDML3LXjNqMNLCzC3wLC1bWbAt@2_000_000_000_000"  --until-level 200_000_000 --protocol-kind Lima'
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    # - run: docker run --rm --name my-sandbox --detach -p 20000:20000 -e block_time=1 oxheadalpha/flextesa:latest kathmandubox start
    - run: npm ci
    - run: npm run build
    - run: npm -w integration-tests run test:originate-known-contracts && npm -w integration-tests run test:kathmandunet-secret-key -- --testPathIgnorePatterns ledger-signer-failing-tests.spec.ts ledger-signer.spec.ts contract-estimation-tests.spec.ts rpc-get-protocol-constants.spec.ts
      env:
        RUN_KATHMANDUNET_WITH_SECRET_KEY: true
        SECRET_KEY: edsk3RFgDiCt7tWB2oe96w1eRw72iYiiqZPLu9nnEY23MYRp2d8Kkx
        TEZOS_RPC_KATHMANDUNET: http://localhost:20000
        POLLING_INTERVAL_MILLISECONDS: 100
        RPC_CACHE_MILLISECONDS: 0
        TEZOS_BAKER: tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
