name: Node.js CI

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 'lts/hydrogen'
          - 'lts/iron'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - run: npm run build
    - run: npm run lint
    - run: npm run build-docs
    - run: npm run test -- --runInBand
    - name: Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        file: .coverage/*.json
      env:
        CI: true
        RUN_INTEGRATION: true

  integration-tests-testnet:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - testnet: oxfordnet
            testnet_uppercase: OXFORDNET
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/hydrogen
    - run: npm ci
    - run: npm run build
    - if: ${{ !github.event.pull_request.head.repo.fork }}
      name: Tailscale
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
        version: 1.32.2
    - run: npm -w integration-tests run test:${{ matrix.testnet }} -- --maxWorkers=4
      env:
        # Ternary operator workaround
        TEZOS_RPC_${{ matrix.testnet_uppercase }}: ${{ github.event.pull_request.head.repo.fork && format('https://{0}.ecadinfra.com', matrix.testnet) || null }}

  integration-tests-flextesa:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - protocol: oxford
            testnet: oxfordnet
            testnet_uppercase: OXFORDNET
            flextesa_docker_image: ghcr.io/tez-capital/tezbox:tezos-v19.1
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/hydrogen

    ## The 4 Bootstrap Accounts (alias, pk, pkh, sk)
    # alice,edpkvGfYw3LyB1UcCahKQk4rF2tvbMUk8GFiTuMjL75uGXrpvKXhjn,tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb,unencrypted:edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq
    # bob,edpkurPsQ8eUApnLUJ9ZPDvu98E8VNj4KtJa1aZr16Cr5ow5VHKnz4,tz1aSkwEot3L2kmUvcoxzjMomb9mvBNuzFK6,unencrypted:edsk3RFfvaFaxbHx8BMtEW1rKQcPtDML3LXjNqMNLCzC3wLC1bWbAt

    - name: Provision Flextesa ${{ matrix.protocol }} container
      run: |-
        docker run \
        --rm \
        --name my-sandbox \
        --detach \
        -p 20000:20000 \
        ${{ matrix.flextesa_docker_image }} \
        ${{ matrix.protocol }}box
    - run: npm ci
    - run: npm run build
    - run: npm -w integration-tests run originate-known-contracts && npm -w integration-tests run test:${{ matrix.testnet }}-secret-key -- --testPathIgnorePatterns integration-tests/__tests__/ledger/ledger-signer-failing-tests.spec.ts integration-tests/__tests__/ledger/ledger-signer.spec.ts integration-tests/__tests__/contract/estimation-tests.spec.ts integration-tests/__tests__/rpc/get-protocol-constants.spec.ts --detectOpenHandles --runInBand
      env:
        RUN_${{ matrix.testnet_uppercase }}_WITH_SECRET_KEY: true
        SECRET_KEY: edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq
        TEZOS_RPC_${{ matrix.testnet_uppercase }}: http://localhost:20000
        POLLING_INTERVAL_MILLISECONDS: 100
        RPC_CACHE_MILLISECONDS: 0
        TEZOS_BAKER: tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
