name: Node.js CI for Flextesa

on:
  push:
    branches:
      - 457-flextesa-kunal-2
jobs:
  integration-tests-flextesanet:
    runs-on: flexteza
    strategy:
      matrix:
        node: [12.x]
    steps:
    - run: echo UUID=$(date +%s) >> $GITHUB_ENV
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/checkout@v2
      with:
        repository: ecadlabs/taquito
        ref: 457-flextesa-kunal-2
        path: taquito_${{ env.UUID }}
    - run: cd taquito_${{ env.UUID }} && npm ci
    - run: cd taquito_${{ env.UUID }} && npm run lerna -- bootstrap
    - run: cd taquito_${{ env.UUID }} && npm run build
    - run: rm -rf ~/.tezos_client/
    - run: docker run --rm --name flextesa_sandbox_${{ env.UUID }} --network github_runner -p 8732:20000 --detach  tqtezos/flextesa:20210602 flobox start   
    - run: sudo add-apt-repository -yu ppa:serokell/tezos && sudo apt-get install -y tezos-client
    - run: tezos-client -A flextesa_sandbox_${{ env.UUID }} -P 20000 import secret key alice unencrypted:edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq --force
    - run: tezos-client -A flextesa_sandbox_${{ env.UUID }} -P 20000 transfer 190000 from alice to tz1Rb18fBaZxkzDgFGAbcBZzxLCYdxyLryVX --burn-cap 0.06425
    - run: tezos-client -A flextesa_sandbox_${{ env.UUID }} -P 20000 transfer 100000 from alice to tz1bwsEWCwSEXdRvnJxvegQZKeX5dj6oKEys --burn-cap 0.06425
    - run: tezos-client -A flextesa_sandbox_${{ env.UUID }} -P 20000 transfer 100000 from alice to tz1ioFRium9QWhYeu49zoAw2Z4HYCHRgrF9f --burn-cap 0.06425  
    - uses: actions/checkout@v2
      with:
        repository: kjaiswal/tezos-key-gen-api
        ref: 457-flextesa-support-kunal
        path: keygen_${{ env.UUID }}
    - run: cd keygen_${{ env.UUID }}/src && sed -i 's/keygen_redis_1/keygen_${{ env.UUID }}_redis_1/g' config.ts
    - run: cd keygen_${{ env.UUID }} && sed -i 's/macmini/flextesa_sandbox_${{ env.UUID }}/g' pools-config.single.json
    - run: cd keygen_${{ env.UUID }} && sed -i 's/keygen_signatory_1/keygen_${{ env.UUID }}_signatory_1/g' pools-config.single.json
    - run: cd keygen_${{ env.UUID }} && docker-compose up &
    - run: cd keygen_${{ env.UUID }} && npm ci
    - run: cd keygen_${{ env.UUID }} && npm run build
    - run: cd keygen_${{ env.UUID }} && npm run start &
    - run: cd taquito_${{ env.UUID }}/example/ && sed -i 's/macmini/flextesa_sandbox_${{ env.UUID }}/g' deploy-flextesa-contracts.ts
    - run: cd taquito_${{ env.UUID }}/example/ && npm run example:deploy-flextesa-contracts
    - run: cd taquito_${{ env.UUID }}/packages/taquito && npm run build
    - run: cd taquito_${{ env.UUID }}/integration-tests/ && sed -i 's/macmini/flextesa_sandbox_${{ env.UUID }}/g' config.ts
    - run: cd taquito_${{ env.UUID }}/integration-tests && npm run test:sandbox -- --maxWorkers=8
      env:
        CI: true
    - run: docker rm -f flextesa_sandbox_${{ env.UUID }} keygen_${{ env.UUID }}_redis_1 keygen_${{ env.UUID }}_signatory_1
